angular.module('app.left.control',[])
       .controller('appLeftController',['$scope',function($scope){
            $scope.listData = [
                {title:"考试管理",body:[{
                    title:"开始考试",
                    routername:'startExam'
                },{
                    title:"历史试卷",
                    routername:'historyPaper'
                }]},
                {title:"工具下载",body:[{
                    title:"学习工具下载",
                    routername:'toolDownload'
                }]},
                {title:"错题管理",body:[{
                    title:"上传错题图片",
                    routername:'wrongTopicManage'
                }]},
                {title:"图片管理",body:[{
                    title:"添加图册",
                    routername:'addImages'
                },{
                    title:"图册列表",
                    routername:'images'
                },{
                    title:"添加图片",
                    routername:'addImage'
                }]}
            ];
       }])
